#!/usr/bin/env node
// website-builder — build the pattern library's specimen sheet.
//
//   node patterns/preview.mjs
//
// Concatenates patterns/sections/*.html into patterns/preview/index.html so a human
// can LOOK at the archetypes rather than read about them. The generated file is
// committed, so nobody has to run this to see the library — running it is for
// after you edit a section.
//
// WHY A GENERATOR AT ALL, given this repo's rule about not adding machinery
// that will not run: because the alternative is a hand-maintained copy of every
// archetype in a second file, and a specimen sheet that has drifted from the
// patterns it claims to show is worse than none. This is twenty lines and it
// runs whenever a section changes.
//
// THE SHEET IS A SPECIMEN SHEET, NOT A PAGE. It holds four heroes, so it has
// four <h1> elements and will trip `seo/h1` and the heading-order gate. That is
// correct and expected: no real page uses four heroes. The families that DO
// apply to a library of shapes — design, a11y, responsive — are asserted by
// `node checks/selftest.mjs`, which is the claim worth making and the one this
// file exists to keep true.

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sectionsDir = join(here, 'sections');

// The order the specimen sheet reads in: chrome, then the shapes a page is
// built from, then the chrome again at the bottom where a footer belongs.
const ORDER = ['hero.html', 'body.html', 'trust.html', 'action.html', 'chrome.html'];
const found = readdirSync(sectionsDir).filter((f) => f.endsWith('.html')).sort();
const missing = found.filter((f) => !ORDER.includes(f));
if (missing.length) {
  // A new section file that nobody added to ORDER would silently not appear.
  // Say so rather than quietly shipping an incomplete sheet.
  console.error(`sections/ has files not in ORDER: ${missing.join(', ')} — add them to patterns/preview.mjs`);
  process.exit(2);
}

// The stylesheet is INLINED rather than linked. Two reasons, and the second is
// the one that matters: the sheet becomes a single portable file anyone can
// open, and `node checks/run.mjs patterns/preview` can actually read the CSS —
// a linked stylesheet one directory up is outside the tree the checker walks,
// so the responsive and design families would have silently checked nothing and
// printed a clean run. That is the exact shape of failure this repo exists to
// stop, and it happened here first.
// The photograph stand-in, drawn as an inline SVG so the sheet stays a single
// portable file with no binaries behind it.
//
// It is a PLATE, not a picture. The first version of this sheet pointed the
// image archetypes at the repo's own synthetic test PNGs and rendered three
// bright pink rectangles, which made a library about restraint look broken. The
// alternative — a stock photograph of somebody's workshop — is the exact
// dishonesty `assets/generated-forbidden-subject` exists to block, so it was
// never available. A drawn plate that says what it is standing in for is the
// third option, and it is the one this repo would tell a client to ship.
const PLATE = 'data:image/svg+xml;utf8,'
  + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 800" role="img">'
    + '<rect width="1200" height="800" fill="#e9e3d8"/>'
    + '<rect x="8" y="8" width="1184" height="784" fill="none" stroke="#cfc6b6" stroke-width="2"/>'
    + '<path d="M8 792 L1192 8" stroke="#e0d8c9" stroke-width="2"/>'
    + '<path d="M8 8 L1192 792" stroke="#e0d8c9" stroke-width="2"/>'
    + '<text x="600" y="416" text-anchor="middle" font-family="Georgia,serif" font-size="34" fill="#847c6d">'
    + 'the client’s photograph</text></svg>');

const parts = ORDER.map((f) => readFileSync(join(sectionsDir, f), 'utf8'))
  // The section files carry SITE-REALISTIC paths, because they are meant to be
  // copied into a build. The sheet swaps them for the plate above.
  .map((s) => s.replace(/src="assets\/photos\/[^"]+"/g, () => `src="${PLATE}"`));

const html = `<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pattern library — website-builder</title>
<meta name="description" content="Twenty-two section archetypes to build a page out of, and the reasons not to use each one.">
<style>
${readFileSync(join(here, 'patterns.css'), 'utf8')}
</style>
<!--
  GENERATED by patterns/preview.mjs. Edit patterns/sections/*.html, not this.

  A specimen sheet, not a page. Four heroes means four h1 elements, which no
  real page has and which the SEO family will correctly object to. The design,
  accessibility and responsive families are the ones that apply here, and
  checks/selftest.mjs asserts them.

  Every business, price, name and photograph on this sheet is invented. The
  phone number is inside Ofcom's drama range for Barnstaple and the email uses
  the reserved .example TLD, so neither can reach a real person.
-->
</head>
<body>
<a class="skip" href="#sheet">Skip to the patterns</a>
<main id="sheet">
${parts.join('\n\n')}
</main>
</body>
</html>
`;

// The sheet lives in its own folder for one reason: `node checks/run.mjs
// patterns/preview` then gates the SHEET and never the fragments. The fragments
// are copy-paste sources with site-realistic paths, not pages, and a checker
// walking them reports missing files that are missing on purpose.
const out = join(here, 'preview', 'index.html');

// --check: generate in memory and compare, without touching the tree. The
// committed sheet is what people look at, so a sheet that has drifted from the
// sections it claims to show is a lie in a folder about not lying. The selftest
// runs this, which is how the drift gets caught rather than noticed.
if (process.argv.includes('--check')) {
  let current = null;
  try { current = readFileSync(out, 'utf8'); } catch { /* below */ }
  if (current === null) {
    console.error('patterns/preview/index.html does not exist. Run: node patterns/preview.mjs');
    process.exit(1);
  }
  // Line endings are the one difference git is allowed to introduce.
  const norm = (t) => t.split('\r\n').join('\n');
  if (norm(current) !== norm(html)) {
    console.error('patterns/preview/index.html is STALE — a section or the stylesheet changed');
    console.error('and the committed sheet was not regenerated. Run: node patterns/preview.mjs');
    process.exit(1);
  }
  console.log('patterns/preview/index.html is current');
  process.exit(0);
}

mkdirSync(join(here, 'preview'), { recursive: true });
writeFileSync(out, html);
console.log(`patterns/preview/index.html written from ${ORDER.length} section files`);
