// website-builder — the asset manifest parser.
//
// `facts.md` made every CLAIM traceable. This is the same idea applied to every
// FILE: an image on the page is a statement about the business — this is our
// shop, this is our team, this is the work we did — and an image nobody can
// trace is exactly as dishonest as a price nobody can trace.
//
// The manifest lives at builds/<slug>/assets/MANIFEST.md and is a markdown
// table, hand-editable, because the client's answer to "is this photo yours to
// publish?" is a sentence, not an enum.

import { existsSync, readFileSync } from 'node:fs';

const EMPTY = /^(|-|—|–|n\/?a|tbd|tbc|todo|unknown|\?+|\.+)$/i;

/** A cell that is present but says nothing is not an answer. */
export const isBlank = (s) => EMPTY.test(String(s || '').trim());

const YES = /^(y|yes|true|generated|ai)$/i;

/** Column aliases, so the table can be written the way a human would write it. */
const COLUMNS = {
  file: /^(file|asset|path|filename)$/,
  kind: /^(kind|type)$/,
  shows: /^(shows|what\s+it\s+shows|subject|description|what)$/,
  source: /^(source|origin|where\s+from|from)$/,
  rights: /^(rights|permission|licence|license|cleared)$/,
  generated: /^(generated|ai|ai-generated|synthetic)$/,
  used: /^(used|used\s+as|usage|where\s+used|placement)$/,
  alt: /^(alt|alt\s+text|alt-text)$/,
};

/**
 * @returns {{rows: object[], hasTable: boolean, imageryPolicy: string|null}}
 */
export function parseManifest(path) {
  if (!path || !existsSync(path)) return { rows: [], hasTable: false, imageryPolicy: null, text: '' };
  const text = readFileSync(path, 'utf8');
  const lines = text.split(/\r?\n/);

  const pol = /^\s*(?:[-*]\s*)?\*{0,2}Imagery(?:\s+policy)?\*{0,2}\s*:\s*`?([a-z][a-z-]*)`?/im.exec(text);
  const imageryPolicy = pol ? pol[1].toLowerCase() : null;

  const rows = [];
  let idx = null;
  let hasTable = false;

  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    if (!raw.trim().startsWith('|')) { idx = null; continue; }
    const cells = raw.trim().replace(/^\||\|$/g, '').split('|').map((c) => c.trim());
    if (cells.every((c) => /^:?-{2,}:?$/.test(c))) continue;

    const lower = cells.map((c) => c.toLowerCase());
    // A header row is one that names a File column and at least one other known
    // column. Anything looser matched the example table inside the instructions.
    const named = Object.entries(COLUMNS)
      .map(([key, re]) => [key, lower.findIndex((c) => re.test(c))])
      .filter(([, at]) => at >= 0);
    if (named.length >= 2 && named.some(([key]) => key === 'file')) {
      idx = Object.fromEntries(named);
      hasTable = true;
      continue;
    }
    if (!idx) continue;

    const cell = (key) => (idx[key] >= 0 ? (cells[idx[key]] ?? '') : '');
    const file = cell('file').replace(/^`|`$/g, '').trim();
    if (!file || /^<.*>$/.test(file)) continue;   // skip template placeholders

    rows.push({
      line: i + 1,
      file,
      kind: cell('kind'),
      shows: cell('shows'),
      source: cell('source'),
      rights: cell('rights'),
      generated: YES.test(cell('generated').trim()),
      generatedCell: cell('generated'),
      used: cell('used'),
      alt: cell('alt'),
      hasRightsColumn: idx.rights >= 0,
      hasAltColumn: idx.alt >= 0,
      hasUsedColumn: idx.used >= 0,
    });
  }

  return { rows, hasTable, imageryPolicy, text };
}

/**
 * Compare a site reference to a manifest row by BASENAME, not by path.
 *
 * The manifest records where the asset came from (`photos/shop-front.jpg`); the
 * site records where it was published (`assets/img/shop-front.jpg`). Those are
 * different strings for the same photograph, and matching on the full path
 * produced a blocker on every correctly-recorded asset — the cry-wolf failure
 * this repo warns about, generated by the check meant to prevent it.
 */
export function basenameKey(p) {
  return String(p)
    .split(/[?#]/)[0]
    .split(/[\\/]/).pop()
    .toLowerCase()
    .trim();
}

/**
 * Subjects a generated image may never depict — the honesty floor from
 * shared/imagery.md §3, expressed so the manifest's own "what it shows" column
 * can be checked against it. Generating one of these is the same offence as
 * inventing a price.
 */
export const FORBIDDEN_GENERATED_SUBJECTS = [
  [/\b(team|staff|owner|founder|employee|colleague|customer|client|patient|portrait|headshot|face|person|people|worker)\b/i,
    'people presented as real'],
  [/\b(shop|store|premises|building|office|workshop|yard|clinic|salon|restaurant|frontage|shopfront|storefront|facility|location)\b/i,
    'premises or locations that do not exist as shown'],
  [/\b(product|item|goods|packaging|bottle|dish|meal|garment)\b/i,
    'a product shown as a genuine photograph'],
  [/\b(logo|wordmark|badge|seal|emblem|as\s+seen\s+in|partner\s+mark|crest)\b/i,
    'logos, wordmarks, badges or partner marks'],
  [/\b(award|certificat|accredit|credential|trophy|qualification)\b/i,
    'awards, certifications or credentials'],
  [/\b(map|chart|graph|infographic|statistic|data)\b/i,
    'maps, charts or infographics asserting real data'],
];
